"""Add latitude and longitude, remove geography

Revision ID: ae4de4783ebb
Revises: 127b2afb6ec7
Create Date: 2025-08-15 22:47:14.667597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'ae4de4783ebb'
down_revision: Union[str, Sequence[str], None] = '127b2afb6ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('businesses', sa.Column('longitude', sa.Float(), nullable=False))
    op.drop_index(op.f('idx_businesses_location'), table_name='businesses', postgresql_using='gist')
    op.drop_column('businesses', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False, _spatial_index_reflected=True), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_businesses_location'), 'businesses', ['location'], unique=False, postgresql_using='gist')
    op.drop_column('businesses', 'longitude')
    op.drop_column('businesses', 'latitude')
    # ### end Alembic commands ###
