"""Update models with optional relationships and cascades

Revision ID: bc0f908ccc23
Revises: 658bca93b769
Create Date: 2025-08-15 15:29:21.338844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc0f908ccc23'
down_revision: Union[str, Sequence[str], None] = '658bca93b769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('businesses', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('businesses_owner_id_key'), 'businesses', type_='unique')
    op.alter_column('profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('profiles_user_id_key'), 'profiles', type_='unique')
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('subscriptions_user_id_key'), 'subscriptions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('subscriptions_user_id_key'), 'subscriptions', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(op.f('profiles_user_id_key'), 'profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(op.f('businesses_owner_id_key'), 'businesses', ['owner_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('businesses', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
